name: Run Check PM2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每6小时触发


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}

          LOG_LEVEL: ${{ secrets.Log_level }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: go run main.go check-pm2

      - name: Append Success Log #追加成功日志
        run: |
          echo "$(date +'%F %T') - check-pm2任务执行成功" >> log/check-pm2.log
      - name: Upload log #上传日志
        uses: actions/upload-artifact@v4
        with:
          name: check-pm2
          path: log/check-pm2.log
      - name: Pull remote changes
        run: git pull
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "check-pm2 log"
          branch: main

